version: '3.8'

services:
  bot:
    build:
      context: ./show_bot
      dockerfile: Dockerfile
    volumes:      
      - ./db.sqlite3:/app/db.sqlite3
    env_file:      
      - './.env'
    # restart: unless-stopped